// Auto generated by build_universal.sh at Mon, Feb 04, 2013  2:40:33 PM

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("0.0.0.0")]
[assembly: AssemblyFileVersion("0.0.0.0")]
[assembly: AssemblyInformationalVersion("See https://github.com/versionone/V1TaskManager/wiki")]

[assembly: AssemblyDescription("VersionOne Task Manager Release Build")]
[assembly: AssemblyCompany("VersionOne, Inc.")]
[assembly: AssemblyProduct("VersionOne Task Manager")]
[assembly: AssemblyTitle("VersionOne Task Manager")]
[assembly: AssemblyCopyright("Copyright 2012-2013, VersionOne, Inc., Licensed under modified BSD.")]

[assembly: AssemblyConfiguration("Release")]
